<template>
  <div class="loadingio-spinner-gear-7oh3q3uheoe">
    <div class="ldio-80llqll6j8k">
      <div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-80llqll6j8k {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(22.5deg);
  }
  100% {
    transform: rotate(45deg);
  }
}
.ldio-80llqll6j8k > div {
  transform-origin: 125.49999999999999px 125.49999999999999px;
  animation: ldio-80llqll6j8k 0.3076923076923077s infinite linear;
}
.ldio-80llqll6j8k > div div {
  position: absolute;
  width: 47.69px;
  height: 185.73999999999998px;
  background: #c3113f;
  left: 125.49999999999999px;
  top: 125.49999999999999px;
  transform: translate(-50%, -50%);
}
.ldio-80llqll6j8k > div div:nth-child(1) {
  width: 155.61999999999998px;
  height: 155.61999999999998px;
  border-radius: 50%;
}
.ldio-80llqll6j8k > div div:nth-child(6) {
  width: 75.3px;
  height: 75.3px;
  background: #ffffff;
  border-radius: 50%;
}
.ldio-80llqll6j8k > div div:nth-child(3) {
  transform: translate(-50%, -50%) rotate(45deg);
}
.ldio-80llqll6j8k > div div:nth-child(4) {
  transform: translate(-50%, -50%) rotate(90deg);
}
.ldio-80llqll6j8k > div div:nth-child(5) {
  transform: translate(-50%, -50%) rotate(135deg);
}
.loadingio-spinner-gear-7oh3q3uheoe {
  width: 251px;
  height: 251px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-80llqll6j8k {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-80llqll6j8k div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
